name: publish

on: [push, workflow_dispatch]

jobs:
  publish-asterisk-build-asl3-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Asterisk Docker Image
        run: |
          docker build . --tag ghcr.io/mkmer/asl3-asterisk-ci:latest
          docker run ghcr.io/mkmer/asl3-asterisk-ci:latest
          docker push ghcr.io/mkmer/asl3-asterisk-ci:latest
        
